version: '2'
services:
    agillity-app:
        image: agillity
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://agillity-mysql:3306/agillity?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    agillity-mysql:
        extends:
            file: mysql.yml
            service: agillity-mysql
